#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /v3/login_check

schema_home:
    path: /schema
    controller: App\Controller\SchemaController::index
    methods: [GET]

schema_path:
    path: /schema/{path}
    controller: App\Controller\SchemaController::withPath
    methods: [GET]
    requirements:
        path: .*

tweede_golf_prometheus:
    resource: "@TweedeGolfPrometheusBundle/Resources/config/routing.yml"
    prefix: /
