#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

schema:
    path: /schema/{path}
    controller: App\Controller\SchemaController::index
    methods: [GET]
    requirements: 
        path: .*
